// <auto-generated />
using System;
using AgroPlan.Property.AgroPlan.Property.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgroPlan.Property.Api.Infrastructure.Migrations
{
    [DbContext(typeof(PropertyContext))]
    [Migration("20200530082644_init_db")]
    partial class init_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Owner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pracels");
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.PhysicalBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhysicalBlocks");
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Owner", b =>
                {
                    b.OwnsOne("AgroPlan.Property.AgroPlan.Core.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("OwnerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnName("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnName("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("AgroPlan.Property.AgroPlan.Core.ValueObjects.Surface", "TotalSurface", b1 =>
                        {
                            b1.Property<string>("OwnerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<float>("Value")
                                .HasColumnName("TotalSurface")
                                .HasColumnType("real");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Parcel", b =>
                {
                    b.HasOne("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Property", null)
                        .WithOne("Parcel")
                        .HasForeignKey("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Parcel", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("AgroPlan.Property.AgroPlan.Core.ValueObjects.Code", "ParcelCode", b1 =>
                        {
                            b1.Property<Guid>("ParcelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnName("ParcelCode")
                                .HasColumnType("int");

                            b1.HasKey("ParcelId");

                            b1.ToTable("Pracels");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.PhysicalBlock", b =>
                {
                    b.HasOne("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Property", null)
                        .WithOne("PhysicalBlock")
                        .HasForeignKey("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.PhysicalBlock", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("AgroPlan.Property.AgroPlan.Core.ValueObjects.Code", "Code", b1 =>
                        {
                            b1.Property<Guid>("PhysicalBlockId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnName("PBCode")
                                .HasColumnType("int");

                            b1.HasKey("PhysicalBlockId");

                            b1.ToTable("PhysicalBlocks");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalBlockId");
                        });
                });

            modelBuilder.Entity("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Property", b =>
                {
                    b.HasOne("AgroPlan.Property.AgroPlan.Core.OwnerAggregate.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("AgroPlan.Property.AgroPlan.Core.ValueObjects.Neighbors", "Neighbors", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("East_Neighbor")
                                .IsRequired()
                                .HasColumnName("EastNeighbor")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("North_Neighbor")
                                .IsRequired()
                                .HasColumnName("NorthNeighbor")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("South_NeighBor")
                                .IsRequired()
                                .HasColumnName("SouthNeighbor")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("West_Neighbor")
                                .IsRequired()
                                .HasColumnName("WestHeighbor")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("AgroPlan.Property.AgroPlan.Core.ValueObjects.Surface", "Surface", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("Value")
                                .HasColumnName("Surface")
                                .HasColumnType("real");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
